# Problem 1

In [14]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.random.randint(0,10,size=5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
multi=a.reshape(5,1)
print(multi)
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[5 0 8 3 1]
(5,)
[[5]
 [0]
 [8]
 [3]
 [1]]
1


# Problem 2

In [22]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
b= np.arange(1, 11, 2).reshape(1,5)
print(b)
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.vsplit(b,[2]))
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([b]))

[[1 3 5 7 9]]
[array([[1, 3, 5, 7, 9]]), array([], shape=(0, 5), dtype=int32)]
[[1 3 5 7 9]]


# Problem 3

In [42]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
c=np.random.randint(5,101,size=10)
print(c)
# 2 - matris'in özelliklerini inceleyin
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[58 68 67 48 37 94 31 61 75 93]
1
(10,)
10
int32
