# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array=np.array([5,23,19,47,11])
print(array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array.sort()
print(array)

[ 5 23 19 47 11]
[ 5 11 19 23 47]


# Problem 2

In [4]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi=np.array([10,15,30,45,60])
print(dizi)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2=np.arange(5,15)
print(dizi2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3=np.arange(50,100,5)
print(dizi3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4=np.zeros(10)
print(dizi4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5=np.ones(10)
print(dizi5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6=np.linspace(0,100,5)
print(dizi6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7=np.random.randint(10,30,5)
print(dizi7)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8=np.random.randint(-1,1,10)
print(dizi8)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
num=np.random.randint(10,50,size=(3,5))
print(num)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(num.sum(axis=0))
print(num.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(num.min())
print(num.max())
print(num.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(num.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
num2=np.random.randint(10,20,size=(3,5))
print(num2)
print(num2[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(num2[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(num2[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(num2[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(num[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(num2**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
num3=np.random.randint(-50,50, size=(3,5))
print((num3>0) & (num3%2==0) )

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[16 22 26 27 14]
[-1  0  0  0  0  0 -1  0 -1 -1]
[[49 47 21 38 45]
 [16 22 19 23 41]
 [25 45 13 42 12]]
[ 90 114  53 103  98]
[200 121 137]
12
49
30.533333333333335
0
[[18 18 19 17 11]
 [10 13 16 16 12]
 [14 14 16 17 13]]
[[18 18 19 17 11]
 [10 13 16 16 12]
 [14 14 16 17 13]]
[[14 14 16 17 13]
 [10 13 16 16 12]
 [18 18 19 17 11]]
[18 18 19 17 11]
16
[49 16 25]
[[324 324 361 289 121]
 [100 169 256 256 144]
 [196 196 256 289 169]]
[[False False False False False]
 [ True  True False  True False]
 [False False False False False]]
